FROM eclipse-temurin:17-jre-focal

EXPOSE 8080

ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD

ENV MYSQL_USERNAME ${MYSQL_USERNAME}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}

ADD build/libs/inq-0.0.1-SNAPSHOT.jar inq-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","inq-0.0.1-SNAPSHOT.jar"]
