server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:43.200.116.136}:${DB_PORT:3306}/${DB_NAME:inq}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:inqdbpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

secret:
  secret-key: ${SECRET_KEY:asdfghgfds}
  access-exp: ${ACCESS_EXP:1800000}
