server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql.xquare.app:${DB_PORT:3306}/${DB_NAME:prod_inq}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:inqdbpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      generate-ddl: false
    defer-datasource-initialization: true
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

secret:
  secret-key: ${SECRET_KEY:asdfghgfds}
  access-exp: ${ACCESS_EXP:1800000}
